apiVersion: v1
kind: Service
metadata:
    name: user-service
spec:
    selector:
        app: user-app
    ports:
        - port: 8080

---
apiVersion: v1
kind: Service
metadata:
    name: password-service
spec:
    selector:
        app: password-app
    ports:
        - port: 8081