apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deploy
  labels:
    app: user-app
spec:
  selector:
    matchLabels:
      app: user-app
  replicas: 1
  template:
    metadata:
      labels:
        app: user-app
      annotations:
        sidecar.istio.io/inject: "true"
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "myapp"
        vault.hashicorp.com/agent-inject-secret-config: "secret/dbconnection"
        vault.hashicorp.com/agent-inject-template-config: |
          {{ with secret "secret/dbconnection" -}}
            export DB_HOST="{{ .Data.data.dbhost }}"
            export DB_PORT="{{ .Data.data.dbport }}"
            export DB_USER="{{ .Data.data.username }}"
            export DB_PASSWORD="{{ .Data.data.password }}"
            export DB_NAME="{{ .Data.data.dbname }}"
            export APP_PORT=":8080"
          {{- end }}
    spec:
      serviceAccountName: app
      containers:
        - name: user-app
          image: shuzasa/user-service:v1.0
          args:
            ['/bin/bash', '-c', 'source /vault/secrets/config && ./app migrate && ./app server']
          ports:
            - name: user-service
              containerPort: 8080

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app
  labels:
    app: user-app

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-app
  ports:
    - port: 8080
