apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deploy
  labels:
    app: user-app
spec:
  selector:
    matchLabels:
      app: user-app
  replicas: 1
  template:
    metadata:
      labels:
        app: user-app
    spec:
      containers:
        - name: user-app
          image: shuzasa/user-service:v1.0
          ports:
            - name: user-service
              containerPort: 8080
          env:
            - name: APP_PORT
              value: ":8080"
            - name: DB_USER
              value: "foobar"
            - name: DB_PASSWORD
              value: "foobar"
            - name: DB_HOST
              value: "postgresql"
            - name: DB_NAME
              value: "learn-db"


---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-app
  ports:
    - port: 8080
